const { withAndroidManifest } = require('expo/config-plugins');

/**
 * Points the launcher's long-press menu at the shortcut definition.
 *
 * The shortcut resource itself lives in the pebble-downloads module, next to
 * the activity it launches, and merges in with that library's manifest. The
 * meta-data tag cannot: it has to hang off the launcher activity, which Expo
 * generates. Hence a plugin rather than a checked-in manifest - `android/` is
 * regenerated by prebuild and any hand edit there is lost.
 */
const META_NAME = 'android.app.shortcuts';

module.exports = function withPebbleShortcuts(config) {
  return withAndroidManifest(config, (mod) => {
    const application = mod.modResults.manifest.application?.[0];
    if (!application) {
      throw new Error('withPebbleShortcuts: no <application> in the manifest');
    }

    const launcher = (application.activity ?? []).find((activity) =>
      (activity['intent-filter'] ?? []).some((filter) =>
        (filter.category ?? []).some(
          (category) =>
            category.$['android:name'] === 'android.intent.category.LAUNCHER',
        ),
      ),
    );
    if (!launcher) {
      throw new Error('withPebbleShortcuts: no launcher activity to attach to');
    }

    launcher['meta-data'] = (launcher['meta-data'] ?? []).filter(
      (item) => item.$['android:name'] !== META_NAME,
    );
    launcher['meta-data'].push({
      $: { 'android:name': META_NAME, 'android:resource': '@xml/shortcuts' },
    });

    return mod;
  });
};
